# Site settings
title: Interrupt | Modern embedded software.
description: "A community for embedded software makers."
url: "https://interrupt.memfault.com"
author:
  name: "Memfault"
  email: "interrupt@memfault.com"
  url: "http://memfault.com"

# Build settings
baseurl: /blog
destination: ./_site
include: 
    - _redirects
markdown: kramdown
permalink: /:title
paginate: 8
paginate_path: /page:num/
source: .

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
