# Site settings
title: Interrupt | Modern embedded software.
description: "A community for embedded software makers."
url: "https://quirky-hugle-cc47ab.netlify.com"
author:
  name: "Memfault"
  email: "interrupt@memfault.com"
  url: "http://memfault.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
